#-----------------------------------------------------------------------------------------------------
# Config for preprocesssing scale images (crop and pad)
#-----------------------------------------------------------------------------------------------------

# path to raw images
raw_img_pth: "Raw Image"

# path to save the preprocessed images
preprocessed_img_pth: "cropped"

# input image type
input_type: ".tif"

# output image type
output_type: ".jpg"

# scale segmentation options are "binary" for binary thresholding and "sam" for Segment Anything
segment: "binary"


# -----Binary Threshold segmentation parameters-----
# binary threshold pixel value for differentiation between foreground (scale) and background
binary_threshold: 100


# -----SAM segmentation parameters-----
# How many points to use for automatic segmentation of scales with SAM.  This should be adjusted based on size of object of interest with respect to the entire image.
# In general, you want number of points to be > ratio of image size/object size for the smallest object of interest.  Having too many points though could greatly increase processing time.
points_per_side: 16

# Threshold for whether to include pixel in object mask.  If the mask is too large, increase the score threshold and vice versa if the mask is too small.
stability_score_thresh: 0.93

# Downsample image size for input to SAM to reduce processing time
downsample: 0.5

# SAM model type.  Options are "vit_b", "vit_l", and "vit_h" in order of increasing size
sam_model_type: "vit_b"

# SAM model weights path.  Make sure this matches the model type.
sam_weights_path: "sam_vit_b_01ec64.pth"


# -----Cropping parameters-----
# Padding for top and sides of cropped image.  Defined as a fraction of the original cropped image size.
pad: 0.2
# Padding for bottom of cropped image.  This is defined separately since for scale images, the bottom is usually visually distinct from the body and may be missed in the segmentation.
bottom_pad: 0.4

# -----Normalization options-----
# After cropping and padding, there is an additional option to normlize the image to normalize the image.  The options are "none", "he" for histogram equalization,
# and "clahe" for Contrast Limited Adaptive Histogram Equalization
normalization: "clahe"
# Option to invert the pixel values in grayscale before normalization.
invert: True


#-----------------------------------------------------------------------------------------------------
# Config for inference 
#-----------------------------------------------------------------------------------------------------

# path to preprocessed image folder
img_path: "cropped"

# path to test csv
test_csv: "train.csv"

# model path
model_path: "weights/multimodal/best_model.pth"

# output path for results
out_path: "result.csv"


#-----------------------------------------------------------------------------------------------------
# Config for training 
#-----------------------------------------------------------------------------------------------------

# path to preprocessed image folder
train_img_path: "cropped"

# path to train csv
train_csv: "train.csv"

# path to validation csv
valid_csv: "train.csv"

# model output path for results
model_out_path: "weights/multimodal"

# number of epochs of training
epochs: 50

# base learning rate
lr: 0.001

# training scheduler checkpoints (learning rate multiplied by gamma at these epoch)
scheduler: [15, 35]

# training scheduler learning rate decay gamma
gamma: 0.1
